import { HumanMessage } from "@langchain/core/messages";
import {
  StateSchema,
  StateGraph,
  type GraphNode,
  START,
  END,
} from "@langchain/langgraph";
import { z } from "zod";
import { mistralModel, cohereModel, geminiModel } from "./ai.service.js";
import { createAgent, providerStrategy } from "langchain";

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistralResponse, cohoreResponse] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: mistralResponse.text,
    solution_2: cohoreResponse.text,
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { solution_1, solution_2, problem } = state;

  const judge = createAgent({
    model: geminiModel,
    tools: [],
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`,
  });

  const judgeRespose = await judge.invoke({
    messages: [
      new HumanMessage(
        ` Problem: ${problem}
          Solution 1: ${solution_1}
          Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `,
      ),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeRespose.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solution", solutionNode)
  .addNode("judge", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge")
  .addEdge("judge", END)
  .compile();

export default async function (userMessage: string) {
  const result = await graph.invoke({
    messages: [new HumanMessage(userMessage)],
  });

  console.log(result);

  return result;
}
